### ISSUE TITLE
Random Regions being selected

### ISSUE THREAD

**Issue by TrantorT** [oracle/oci-toolkit-eclipse#11]
I have Frankfurt in my preferences but items are being created at random regions.

Created a new Bucket - went to Phoenix
A new ADB - Zurich

Also they both went to root compartment, while i did select my own compartment (for the ADB)

---------------

EDIT: this item can be closed as it is not an issue - just some wrong configurations

**Comment by jyotisaini** [comment]
Thanks @TrantorT for providing an update. I had tried to reproduce this but I was not able to. Closing this issue.
