### ISSUE TITLE
Configuration doesn't work if ~/.oci/config doesn't contains DEFAULT profile

### ISSUE THREAD

**Issue by Madzi** [oracle/oci-toolkit-eclipse#8]
I have 5 profiles into my `~/.oci/config` file, but all of them has own names (so no DEFAULT configuration). When I use `OCI CLI` or from my Java code it's work fine.
The global eclipse settings on `Oracle Cloud Infrastructure Preferences` tab show me message about wrong OCI configuration and doesn't give me a chance to choose any active profile from my configuration

**Comment by nalsaber** [comment]
Thanks Dmitry for reporting this. We will get it fixed in the coming release.
As a work around, you can add a DEFAULT in the config file.

**Comment by jyotisaini** [comment]
Hi @Madzi This issue has been fixed with the latest release(v1.31).  Can you give it a try before we close the issue? Thanks.

**Comment by jyotisaini** [comment]
This is fixed.

**Comment by Madzi** [comment]
Thank you. It's work now.
